# Lecture 9: Functions #

In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Histogram Example

In [ ]:
# From https://womenintheworld.org/highest-paid-actress/
incomes = Table.read_table('2022_female_actors.csv')
incomes.show(3)

In [ ]:
my_bins = make_array(0, 25, 30, 60)
incomes.hist('Income (millions)', bins=my_bins)

In [ ]:
min(incomes.column(1))

In [ ]:
my_bins = make_array(min(incomes.column(1)), 25, 30, 60)
incomes.hist('Income (millions)', bins=my_bins)
plots.xticks(np.arange(12.5,62.6,10));

## Defining Functions ##  

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [ ]:
def triple(x):
    return 3 * x

In [ ]:
triple(3)

We can also assign a value to a name, and call the function on the name:

In [ ]:
num = 4

In [ ]:
triple(num)

In [ ]:
triple(num * 5)

## The Anatomy of a Function ##  
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
      return return_expression
```

## Functions are Type-Agnostic  ## 

In [ ]:
triple('ha')

In [ ]:
np.arange(4)

Feed the array above into our function `triple` to see what is produced:

In [ ]:
triple(np.arange(4))

### Discussion ###

- What does the following function do?
- What type of input does it take?
- What type of output does it produce?
- What's a good name for the function?

```python
def f(s):     
      return np.round(s / sum(s) * 100, 2)
```

In [ ]:
def ...(s):
    return np.round(s / sum(s) * 100, 2)

In [ ]:
first_four=make_array(1,2,3,4)
first_four

In [ ]:
...(first_four)

In [ ]:
...(make_array(1, 213, 38))

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

In [ ]:
def hypotenuse(x, y):
    hypot_squared = (x ** 2 + y ** 2)
    hypot = hypot_squared ** 0.5
    return hypot

In [ ]:
hypotenuse(1, 2)

In [ ]:
hypotenuse(3, 4)

### Example: A function that takes the year of birth of a person and produces their age in years. ###

In [5]:
def age(year):
    age = 2023 - year
    return age

In [ ]:
age(1942)

Now add some bells and whistles:  Take person's name and year of birth (two arguments). Produce a sentence that states how old they are.

In [10]:
def name_and_age(name, year):
    return name + ' is ' + str(age(year)) + ' years old.'

In [ ]:
name_and_age('Joe', 1942)

## Apply ##

In [3]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
ages

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [6]:
ages.apply(age, 'Birth Year')

array([ 38,  35,  56, 119])

In [7]:
make_array(age(ages.column('Birth Year').item(0)),
           age(ages.column('Birth Year').item(1)),
           age(ages.column('Birth Year').item(2)),
           age(ages.column('Birth Year').item(3)))

array([ 38,  35,  56, 119])

In [8]:
age(ages.column('Birth Year'))

array([ 38,  35,  56, 119])

In [11]:
ages.apply(name_and_age, 'Person', 'Birth Year')

array(['Jim is 38 years old.', 'Pam is 35 years old.',
       'Michael is 56 years old.', 'Creed is 119 years old.'],
      dtype='<U24')